In [20]:
#Numpy
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [21]:
import numpy as np
a=np.array([10,20,30,40])
zeros=np.zeros(5)   #zero matrix
ones=np.ones((2,3)) #ones matrix
r=np.arange(0,10,2) #arrange
ls=np.linspace(0,1,5) #linspacing
eye=np.eye(3)         #identity matrix


In [22]:
print(zeros)

[0. 0. 0. 0. 0.]


In [23]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(r)

[0 2 4 6 8]


In [25]:
print(ls)

[0.   0.25 0.5  0.75 1.  ]


In [26]:
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#Array dimensions and shape
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim) #no of axes
print(a.shape) #rows and colums
print(a.size) #size
print(a.dtype) #daratype

2
(2, 3)
6
int64


In [40]:
#Numpy operations
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b) #addition
print(a-b) #substraction
print(a**b) #multiplication
print(np.sqrt(a)) #sqroot
print(np.dot(a,b)) #1*4 + 2*5 +3*6=32 

[5 7 9]
[-3 -3 -3]
[  1  32 729]
[1.         1.41421356 1.73205081]
32


In [47]:
a=np.array([3,1,4,1,5,9,2,6])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))
print(np.argmax(a))

m=np.array([[1,2,3],[4,5,6]])
print(np.sum(m,axis=0)) #col sum
print(np.sum(m,axis=1)) #row sum

31
3.875
3.5
2.5708704751503917
1
9
5
[5 7 9]
[ 6 15]
